//# Generated by MakeApp
//# No template found for: main.js.j2

import { createApp } from 'vue'
import App from './App.vue'
import router from './router'

const app = createApp(App)
app.use(router)
app.mount('#app')
